# Generated by Django 5.1 on 2024-11-10 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowTestApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='folder_id',
        ),
        migrations.AddField(
            model_name='testcase',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to='FlowTestApp.folder'),
        ),
        migrations.AlterField(
            model_name='automationscript',
            name='test_case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FlowTestApp.testcase'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='FlowTestApp.role'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='test_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_runs', to='FlowTestApp.testcase'),
        ),
    ]
