# Generated by Django 5.1 on 2024-11-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowTestApp', '0005_folder_parent_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('de', 'Deutsch')], default='en', max_length=10, verbose_name='Предпочитаемый язык'),
        ),
    ]
