# Generated by Django 5.1 on 2024-12-19 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowTestApp', '0011_testreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('start', 'Test Started'), ('step_complete', 'Step Completed'), ('error', 'Error Occurred'), ('warning', 'Warning'), ('info', 'Information'), ('finish', 'Test Finished')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='info', max_length=20)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='test_events/screenshots/')),
                ('log_file', models.FileField(blank=True, null=True, upload_to='test_events/logs/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='FlowTestApp.testcase')),
                ('test_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='FlowTestApp.testreport')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='FlowTestApp_timesta_880a13_idx'), models.Index(fields=['event_type'], name='FlowTestApp_event_t_fdd498_idx'), models.Index(fields=['severity'], name='FlowTestApp_severit_78c6a3_idx')],
            },
        ),
    ]
