# Generated by Django 5.1.3 on 2025-01-07 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowTestApp', '0012_testevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationscript',
            name='framework',
            field=models.CharField(choices=[('pytest', 'PyTest'), ('unittest', 'UnitTest'), ('robot', 'Robot Framework'), ('cypress', 'Cypress'), ('selenium', 'Selenium'), ('playwright', 'Playwright'), ('other', 'Other')], default='pytest', max_length=50),
        ),
        migrations.AddField(
            model_name='automationscript',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FlowTestApp.project'),
        ),
        migrations.AddField(
            model_name='schedulerevent',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulerevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='schedulerevent',
            name='test_config',
            field=models.JSONField(blank=True, help_text='Configuration for test execution: {"run_all_project_tests": true} or {"folder_id": 123} or {"test_cases": [1, 2, 3]}', null=True),
        ),
        migrations.AlterField(
            model_name='schedulerevent',
            name='event_type',
            field=models.CharField(choices=[('run_tests', 'Run Tests'), ('general', 'General Event')], default='general', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='automationscript',
            unique_together={('project', 'script_path')},
        ),
        migrations.CreateModel(
            name='AutomationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('repository_url', models.URLField()),
                ('branch', models.CharField(default='main', max_length=100)),
                ('framework', models.CharField(choices=[('pytest', 'PyTest'), ('unittest', 'UnitTest'), ('robot', 'Robot Framework'), ('playwright', 'Playwright')], max_length=20)),
                ('local_path', models.CharField(blank=True, max_length=255, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('synced', 'Synced'), ('not_synced', 'Not Synced'), ('error', 'Error')], default='not_synced', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_projects', to='FlowTestApp.project')),
            ],
        ),
        migrations.CreateModel(
            name='AutomatedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('test_name', models.CharField(max_length=255)),
                ('code', models.TextField()),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('synced', 'Synced'), ('modified', 'Modified in Test Case'), ('different', 'Different from Source'), ('not_found', 'Not Found in Source')], default='synced', max_length=50)),
                ('test_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='automated_test', to='FlowTestApp.testcase')),
                ('automation_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='FlowTestApp.automationproject')),
            ],
        ),
    ]
