# Generated by Django 5.1 on 2025-01-07 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowTestApp', '0013_automationscript_framework_automationscript_project_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='automationscript',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='automationscript',
            name='project',
        ),
        migrations.RemoveField(
            model_name='automationscript',
            name='test_case',
        ),
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='testcase',
            name='automation_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to='FlowTestApp.automationproject'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='framework',
            field=models.CharField(blank=True, choices=[('pytest', 'PyTest'), ('unittest', 'UnitTest'), ('robot', 'Robot Framework'), ('cypress', 'Cypress'), ('selenium', 'Selenium'), ('playwright', 'Playwright'), ('other', 'Other')], default='pytest', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='script_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='AutomatedTest',
        ),
        migrations.DeleteModel(
            name='AutomationScript',
        ),
    ]
