# Generated by Django 5.1 on 2025-01-07 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FlowTestApp', '0015_automationproject_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testschedule',
            old_name='time',
            new_name='schedule_time',
        ),
        migrations.RemoveField(
            model_name='testschedule',
            name='type',
        ),
        migrations.RemoveField(
            model_name='testschedule',
            name='days',
        ),
        migrations.AddField(
            model_name='testschedule',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testschedule',
            name='last_status',
            field=models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='testschedule',
            name='last_result',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testschedule',
            name='tests',
            field=models.ManyToManyField(blank=True, to='FlowTestApp.automationtest'),
        ),
    ]
