# Generated by Django 5.1 on 2025-01-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowTestApp', '0016_auto_20250107_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationproject',
            name='access_token',
            field=models.CharField(blank=True, help_text='Personal access token for private repositories', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='automationproject',
            name='repository_type',
            field=models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket')], default='github', max_length=20),
        ),
        migrations.AddField(
            model_name='automationproject',
            name='username',
            field=models.CharField(blank=True, help_text='Username for private repositories', max_length=100, null=True),
        ),
    ]
