# Generated by Django 5.1 on 2025-01-07 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowTestApp', '0017_automationproject_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationproject',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_projects', to='FlowTestApp.project'),
        ),
    ]
