# Generated by Django 5.1 on 2025-01-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowTestApp', '0018_alter_automationproject_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=50),
        ),
    ]
