# Generated by Django 5.1 on 2025-01-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowTestApp', '0021_automationtest_framework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testrun',
            old_name='run_at',
            new_name='started_at',
        ),
        migrations.AddField(
            model_name='testrun',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='framework',
            field=models.CharField(choices=[('pytest', 'PyTest'), ('unittest', 'UnitTest'), ('robot', 'Robot Framework'), ('playwright', 'Playwright')], default='pytest', max_length=20),
        ),
        migrations.AddField(
            model_name='testrun',
            name='log_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error'), ('skipped', 'Skipped')], default='pending', max_length=50),
        ),
    ]
