# Generated by Django 5.1.3 on 2025-01-19 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowTestApp', '0022_rename_run_at_testrun_started_at_testrun_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrun',
            name='framework',
        ),
        migrations.AlterField(
            model_name='testrun',
            name='duration',
            field=models.FloatField(help_text='Duration in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='test_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FlowTestApp.testcase'),
        ),
    ]
