# Generated by Django 5.1.3 on 2025-01-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowTestApp', '0024_reporttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
