# Generated by Django 5.1.3 on 2025-02-02 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FlowTestApp", "0025_testcase_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("line", "Line Chart"),
                            ("bar", "Bar Chart"),
                            ("pie", "Pie Chart"),
                            ("doughnut", "Doughnut Chart"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("test_status", "Test Status"),
                            ("user_activity", "User Activity"),
                            ("daily_trends", "Daily Trends"),
                            ("custom_query", "Custom Query"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        default=dict, help_text="Chart-specific configuration"
                    ),
                ),
                (
                    "custom_query",
                    models.TextField(
                        blank=True,
                        help_text="SQL query for custom data source",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_charts",
                        to="FlowTestApp.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
