# Generated by Django 5.1 on 2025-02-17 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FlowTestApp", "0026_customchart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testrun",
            old_name="log_output",
            new_name="output",
        ),
        migrations.RemoveField(
            model_name="testrun",
            name="duration",
        ),
        migrations.AddField(
            model_name="testcase",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_cases",
                to="FlowTestApp.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testrun",
            name="execution_time",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="testrun",
            name="executor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="testrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                    ("error", "Error"),
                    ("skipped", "Skipped"),
                ],
                max_length=20,
            ),
        ),
    ]
