# Generated by Django 5.1.3 on 2025-02-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FlowTestApp", "0027_rename_log_output_testrun_output_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.BinaryField(
                blank=True, editable=True, null=True, verbose_name="Avatar Image Data"
            ),
        ),
    ]
