# Generated by Django 5.1.3 on 2025-02-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FlowTestApp", "0028_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
