# Generated by Django 5.1.3 on 2025-02-23 09:37

import FlowTestApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FlowTestApp", "0029_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=FlowTestApp.models.avatar_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("ru", "Russian"), ("de", "German")],
                default="en",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="theme",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark")],
                default="light",
                max_length=10,
            ),
        ),
    ]
