# Generated by Django 5.1.3 on 2025-02-23 12:20

import FlowTestApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "FlowTestApp",
            "0030_alter_customuser_avatar_alter_customuser_language_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="middle_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="role",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=FlowTestApp.models.avatar_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("ru", "Русский")],
                default="en",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
