# Generated by Django 5.1.3 on 2025-02-23 12:34

import FlowTestApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FlowTestApp", "0032_remove_role_permissions_customuser_middle_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=FlowTestApp.models.avatar_upload_path
            ),
        ),
    ]
