# Generated by Django 5.1.3 on 2025-03-01 15:36

import FlowTestApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FlowTestApp", "0033_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="reporttemplate",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=FlowTestApp.models.avatar_upload_path,
            ),
        ),
    ]
