# Generated by Django 5.1 on 2025-03-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FlowTestApp", "0034_reporttemplate_is_deleted_alter_customuser_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("codename", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("user_management", "Управление пользователями"),
                            ("project_management", "Управление проектами"),
                            ("test_management", "Управление тестами"),
                            ("reporting", "Отчеты"),
                            ("admin", "Администрирование"),
                        ],
                        default="test_management",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.AddField(
            model_name="role",
            name="is_admin_role",
            field=models.BooleanField(
                default=False, help_text="Администраторская роль с полным доступом"
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                blank=True, related_name="roles", to="FlowTestApp.permission"
            ),
        ),
    ]
